#!/bin/bash

FOLDER=$1
GIT_URL=$2
case $1 in
  'chat' | 'chat-pane')
    FOLDER='chat-pane'
    GIT_URL='https://github.com/solid/chat-pane'
    ;;
  'contacts' | 'contacts-pane')
    FOLDER='contacts-pane'
    GIT_URL='https://github.com/solid/contacts-pane'
    ;;
  'folder' | 'folder-pane')
    FOLDER='folder-pane'
    GIT_URL='https://github.com/solid/folder-pane'
    ;;
  'issue' | 'issue-pane')
    FOLDER='issue-pane'
    GIT_URL='https://github.com/solid/issue-pane'
    ;;
  'mashlib')
    GIT_URL='https://github.com/solid/mashlib'
    ;;
  'meeting' | 'meeting-pane')
    FOLDER='meeting-pane'
    GIT_URL='https://github.com/solid/meeting-pane'
    ;;
  'node-solid-server')
    GIT_URL='https://github.com/solid/node-solid-server'
    ;;
  'pane-registry' | 'registry')
    GIT_URL='https://github.com/solid/pane-registry'
    ;;
  'rdflib')
    GIT_URL='https://github.com/linkeddata/rdflib.js.git'
    ;;
  'solid-auth-client')
    GIT_URL='https://github.com/solid/solid-auth-client.git'
    ;;
  'solid-namespace')
    GIT_URL='https://github.com/solid/solid-namespace'
    ;;
  'solid-panes')
    GIT_URL='https://github.com/solid/solid-panes'
    ;;
  'solid-ui')
    GIT_URL='https://github.com/solid/solid-ui'
    ;;
  'source' | 'source-pane')
    FOLDER='source-pane'
    GIT_URL='https://github.com/solid/source-pane'
    ;;
esac

if test -z "$GIT_URL"
then
  echo "repo not recognized, please provide URL to Git repo"
  exit 1
fi

echo $GIT_URL

echo ">>>>> ADDING REPO - $GIT_URL to $FOLDER"
cd workspaces
git clone $GIT_URL $FOLDER
cd $FOLDER
nvm use
npm i
cd ../..
